import Head from 'next/head'
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.cdnfonts.com/css/hk-groteks" rel="stylesheet"/>
      </Head>
      <main className="font-['HK_Grotesk']">
        <Image alt="" src="/vector-1.svg" width={271} height={257} className="fixed"/>
        <Image alt="" src="/vector-2.svg" width={402} height={375} className="fixed left-48 top-48" />
        <Image alt="" src="/vector-3.svg" width={472} height={429} className="fixed bottom-10 right-10"/>
        <Image alt="" src="/vector-4.svg" width={650} height={501} className="fixed bottom-10 left-28"/>
        <Image alt="" src="/vector-5.svg" width={300} height={231} className="fixed top-10 right-28"/>
        <Image alt="" src="/vector-6.svg" width={506} height={470} />
        <div className="backdrop-blur-[75px] bg-white/50 fixed inset-0 text-6xl flex items-center justify-center">
          <div className="bg-[#307765] text-white shadow-[0_0_30px_50px_rgba(48,119,101,1)] font-bold" >
            Bientôt disponible
          </div>
        </div>
      </main>
    </>
  )
}
