import Head from 'next/head'
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
        <link href="https://fonts.cdnfonts.com/css/hk-groteks" rel="stylesheet"/>
      </Head>
      <main className="font-['HK_Grotesk']">
        <Image alt="" src="/vector-1.svg" width={271} height={257} className="fixed"/>
        <Image alt="" src="/vector-2.svg" width={402} height={375} className="fixed left-48 top-48"/>
        <Image alt="" src="/vector-3.svg" width={472} height={429} className="fixed bottom-10 right-10"/>
        <Image alt="" src="/vector-4.svg" width={650} height={501} className="fixed bottom-10 left-28"/>
        <Image alt="" src="/vector-5.svg" width={300} height={231} className="fixed top-10 right-28"/>
        <Image alt="" src="/vector-6.svg" width={506} height={470}/>
        <div className="backdrop-blur-[75px] bg-white/50 fixed inset-0 flex justify-center p-[50px] overflow-y-auto">
          <div className="max-w-[1380px] w-full relative flex flex-col">
            <div className="border-primary-900 border-2 fixed flex items-center">
              <div className="px-5 py-3 border-primary-900 border-r-2 text-primary-900 font-bold text-3xl">
                Agreenup
              </div>
              <div className="px-5 py-2 text-primary-900 font-bold flex space-x-10 items-center text-lg">
                <span>La permaculture</span>
                <span>À propos</span>
                <span>Les formations</span>
                <button className="px-5 py-1.5 bg-primary-900 text-white rounded-[40px]">Réserver une formation</button>
              </div>
            </div>
            <div className="border-primary-900 border-2 border-b-0 pt-40 pb-24 pl-40 pr-60 flex gap-32">
              <div className="w-1/2 items-center flex">
                <div className="text-primary-900">
                  <span className="text-5xl mb-5 block w-80">Apprendre la permaculture en 2h30</span>
                  <p className="w-full">Produire son potager et ses plantes décoratives en résilience avec la sécheresse grâce aux méthodes culturales naturelles.</p>
                  <button className="px-5 py-1.5 bg-primary-900 text-white rounded-[40px] mt-8">Réserver une formation</button>
                </div>
              </div>
              <div className="w-1/2 flex flex-col gap-6 items-center">
                <img src="http://placekitten.com/323/323" alt=""/>
                <img src="http://placekitten.com/323/323" alt=""/>
              </div>
            </div>
            <div className="flex flex-row w-full">
              <div className="w-1/2 border-t-2 border-primary-900"></div>
              <div className="w-1/2 border-x-2 border-b-2 border-primary-900 h-20"></div>
            </div>
            <div className="flex w-full justify-center">
              <div className="flex flex-col w-full max-w-[1020px] -mt-[2px]">
                <div className="w-full flex">
                  <div className="w-1/2 border-l-2 border-t-2 border-r-0 border-primary-900 text-5xl text-primary-900 flex items-center px-10">
                    <span>La permaculture</span>
                  </div>
                  <div className="w-1/2 border-l-2 border-b-0 border-primary-900 h-20"></div>
                </div>
                <div className="border-2 border-b-0 border-primary-900 px-12 py-24 flex gap-10">
                  <div className="grid grid-cols-2 gap-5 w-1/2">
                    <img src="http://placekitten.com/255/255" alt=""/>
                    <img src="http://placekitten.com/255/255" alt=""/>
                    <img src="http://placekitten.com/255/255" alt=""/>
                    <img src="http://placekitten.com/255/255" alt=""/>
                  </div>
                  <div className="w-1/2">
                    <p className="text-lg text-primary-900">Le Développement Durable est une façon de penser, de vivre en collectivité avec la Nature. Il y a différents domaines, c'est une philosophie de vie, un concept que l'on peut tous appliquer pour les générations présentes et futures.</p>
                  </div>
                </div>
                <div className="flex flex-row w-full">
                  <div className="w-1/2 border-t-2 border-primary-900"></div>
                  <div className="w-1/2 border-x-2 border-primary-900 h-20"></div>
                </div>
              </div>
            </div>
            <div className="border-primary-900 border-2 border-b-0 pt-40 pb-24 pl-40 pr-60 flex gap-32">
              <div className="w-1/2 items-center flex">
                <div className="text-primary-900">
                  <span className="text-5xl mb-5 block w-80">Je suis Laurent Jacozs, formateur</span>
                  <p className="w-full">Cheesy grin mascarpone the big cheese goat fromage frais hard cheese port-salut paneer. Queso bavarian bergkase everyone loves camembert de normandie cheese and biscuits mascarpone blue castello chalk and cheese. Manchego cut the cheese.</p>
                  <button className="px-5 py-1.5 bg-primary-900 text-white rounded-[40px] mt-8">En savoir plus</button>
                </div>
              </div>
              <div className="w-1/2 flex flex-col gap-6 items-center">
                <img src="http://placekitten.com/485/485" alt=""/>
              </div>
            </div>
            <div className="flex flex-row w-full">
              <div className="w-1/2 border-x-2 border-b-2 border-primary-900 h-20"></div>
              <div className="w-1/2 border-t-2 border-primary-900"></div>
            </div>
            <div className="flex w-full justify-center">
              <div className="flex flex-col w-full max-w-[1020px] -mt-[2px]">
                <div className="w-full flex">
                  <div className="w-1/2 border-r-2 border-b-0 border-primary-900 h-20"></div>
                  <div className="w-1/2 border-r-2 border-t-2 border-primary-900 text-5xl text-primary-900 flex items-center px-10">
                    <span>La permaculture</span>
                  </div>
                </div>
                <div className="border-2 border-b-0 border-primary-900 px-12 py-24 flex gap-10">
                  <div className="grid grid-cols-2 gap-5 w-1/2">
                    <img src="http://placekitten.com/255/255" alt=""/>
                    <img src="http://placekitten.com/255/255" alt=""/>
                    <img src="http://placekitten.com/255/255" alt=""/>
                    <img src="http://placekitten.com/255/255" alt=""/>
                  </div>
                  <div className="w-1/2">
                    <p className="text-lg text-primary-900">Le Développement Durable est une façon de penser, de vivre en collectivité avec la Nature. Il y a différents domaines, c'est une philosophie de vie, un concept que l'on peut tous appliquer pour les générations présentes et futures.</p>
                  </div>
                </div>
                <div className="flex flex-row w-full">
                  <div className="w-1/2 border-t-2 border-primary-900"></div>
                  <div className="w-1/2 border-x-2 border-primary-900 h-20"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
